### ISSUE TITLE
New API to create a Simulations and Tasks

### ISSUE THREAD

**Issue by buehlefs** [FIUS/ICGE2#140]
We want a easy to use api to create a new simulation.

~~One simulation builder can only be used to create exactly one simulation.~~

```java
Simulation simulation = new Simulation(new Task1Verifier()); // verifier is an optional parameter
simulation.runTask(new Task1()); // this runs the task in a background thread, task must implement Task interface for this!
simulation.start(); // this can also be done with the play button in the ui
new Task1().run(simulation); // this must happen after simulation.start() (task contains blocking calls...)
```

**Comment by buehlefs** [comment]
This issue strongly depends on #137

**Comment by marzipankaiser** [comment]
In the text, a simulation builder is mentioned. However, in the code there is none. Is that intended?

**Comment by buehlefs** [comment]
The plan was to use a SimulationBuilder but i noticed that we only set a task verifyer. There is no need for a special builder. The constructor for simulation can also support setting the task verifier.

**Comment by neumantm** [comment]
Actually a SimulationBuilder would be useful. It makes it consistent to Window. And we do not need to expose the implementation of Simulation (or a wrapper of it), but only an Interface
