### ISSUE TITLE
When calling Simulation.start() the UI buttons do not update correctly

### ISSUE THREAD

**Issue by neumantm** [FIUS/ICGE2#48]

**Comment by mee4895** [comment]
Why, how ?? Is the clock correctly attached to the proxy ? Does the Simulation.start() call the clock.start()?

**Comment by neumantm** [comment]
Look at the mario example

**Comment by buehlefs** [comment]
The simulation clock should not be started in the solve method of a task. The user is responsible for pressing the play button himself.

**Comment by mee4895** [comment]
What is the expected button state and what is the actual button state??

**Comment by mee4895** [comment]
If I read the code correctly then the SimulationHostFactory never creates a Simulation or SimulationClock thus the buttons stay dissabled. This is all not a bug but expected behaviour.

**Comment by buehlefs** [comment]
The simulation and its clock are only created by the SimulationHost when a task is selected.

**Comment by neumantm** [comment]
It seams like this was fixed by #54

**Comment by neumantm** [comment]
> The simulation clock should not be started in the solve method of a task. The user is responsible for pressing the play button himself.

I agree that this should not be the normal procedure. But I'd like to have that possibility for some special cases.

**Comment by neumantm** [comment]
> It seams like this was fixed by #54

I will close this issue. Please reopen if this is not really the case.
